In [1]:
#https://www.kaggle.com/c/the-nature-conservancy-fisheries-monitoring
import numpy as np
import os
import cv2
from sklearn.preprocessing import LabelBinarizer
import tflearn
from tflearn.layers.conv import conv_2d, max_pool_2d
from tflearn.layers.core import input_data, dropout, fully_connected
from tflearn.layers.estimator import regression


curses is not supported on this machine (please install/reinstall curses for an optimal experience)


In [2]:
traindir='D:\\fish\\train'  #the directory where you extracted the training data
lab=[i for i in os.listdir(traindir)]
label=LabelBinarizer().fit_transform(lab)
print(label)

[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]


In [3]:
trainset=[]
for i in lab:
    for n in os.listdir(os.path.join(traindir,i)):
        path=os.path.join(traindir,i,n)
        img=cv2.resize(cv2.imread(path,cv2.IMREAD_GRAYSCALE),(50,50))
        trainset.append([np.array(img),label[lab.index(i)]])


In [ ]:
test_x=np.array([i[0] for i in trainset[:1133]]).reshape(-1,50,50,1)
test_y=[i[1] for i in trainset[:1133]]
train_x=np.array([i[0] for i in trainset[1133:]]).reshape(-1,50,50,1)
train_y=([i[1] for i in trainset[1133:]])

print(len(train_x))






2644


In [ ]:
test_x=np.array([i[0] for i in trainset[:1133]]).reshape(-1,50,50,1)
test_y=[i[1] for i in trainset[:1133]]
train_x=np.array([i[0] for i in trainset[1133:]]).reshape(-1,50,50,1)
train_y=[i[1] for i in trainset[1133:]]


convnet = input_data(shape=[None,50, 50,1], name='input')
convnet = conv_2d(convnet, 32, 2, activation='relu')
convnet = max_pool_2d(convnet, 2)

convnet = conv_2d(convnet, 64, 2, activation='relu')
convnet = max_pool_2d(convnet, 2)

convnet = conv_2d(convnet, 32, 2, activation='relu')
convnet = max_pool_2d(convnet, 2)

convnet = conv_2d(convnet, 64, 2, activation='relu')
convnet = max_pool_2d(convnet, 2)

convnet = conv_2d(convnet, 32, 2, activation='relu')
convnet = max_pool_2d(convnet, 2)

convnet = conv_2d(convnet, 64, 2, activation='relu')
convnet = max_pool_2d(convnet, 2)

convnet = conv_2d(convnet, 32, 2, activation='relu')
convnet = max_pool_2d(convnet, 2)

convnet = conv_2d(convnet, 64, 2, activation='relu')
convnet = max_pool_2d(convnet, 2)

convnet = conv_2d(convnet, 32, 8, activation='relu')
convnet = max_pool_2d(convnet, 2)

convnet = conv_2d(convnet, 64, 8, activation='relu')
convnet = max_pool_2d(convnet, 2)

convnet = fully_connected(convnet, 1024, activation='relu')
convnet = dropout(convnet, 0.8)

convnet = fully_connected(convnet, 8, activation='softmax')
convnet = regression(convnet, optimizer='adam', learning_rate=1e-6, loss='categorical_crossentropy', name='targets')

model = tflearn.DNN(convnet)


model.fit({'input': train_x}, {'targets': train_y}, n_epoch=100, validation_set=({'input': test_x}, {'targets': test_y}), snapshot_step=500, show_metric=True)
model.save('cnnmodel.tfl')

Training Step: 44  | total loss: 2.07939 | time: 0.203s
| Adam | epoch: 002 | loss: 2.07939 - acc: 0.1429 -- iter: 0128/2644
